In [2]:
import pandas as pd

In [3]:
rejections = pd.read_csv('rejections.csv')

In [4]:
rejections

,date_received,ingredient_name,supplier,number_of_cases,units_per_case,sample_case_count1,sample_case_count2,sample_case_count3,sample_case_rejections1,sample_case_rejections2,sample_case_rejections3
0,10-Jun-21,tomato_cherry,ABC Vegetables,10,100,95,100,110,5,3,5
1,10-Jun-21,tomato_cherry,Tomato Land,20,500,440,480,500,10,0,25
2,10-Jun-21,tomato_vine,Tomato Land,25,100,100,100,100,0,0,0
3,10-Jun-21,tomato_vine,ABC Vegetables,10,100,100,98,101,0,0,0
4,10-Jun-21,cucumber_english,ABC Vegetables,14,50,51,50,51,10,0,0
5,10-Jun-21,cucumber_pickle,Dill Farms,15,50,50,50,50,0,0,0
6,11-Jun-21,bananas_organic,Banana Farms Inc,24,40,40,40,40,0,0,0
7,11-Jun-21,bananas_organic,ABC Vegetables,26,30,30,28,29,0,3,0
8,11-Jun-21,bananas_organic,Banana Farms Inc,20,30,30,30,30,0,0,0
9,11-Jun-21,apples_gala,Orchard Inc,20,90,90,94,90,1,4,5
10,11-Jun-21,apples_gala,Orchard Inc,5,90,90,90,90,0,0,3
11,11-Jun-21,apples_gs,Orchard Inc,1,80,80,82,80,2,0,5
12,13-Jun-21,apples_gala,Apple Farm,20,90,90,90,90,0,0,0
13,13-Jun-21,oranges_california,Cali Fruits,20,90,90,90,90,4,0,0
14,13-Jun-21,oranges_california,ABC Vegetables,40,100,100,102,101,0,0,3
15,13-Jun-21,grapes_red,Cali Fruits,20,35,30,35,30,4,0,0
16,13-Jun-21,grapes_green,Cali Fruits,10,35,35,35,30,5,5,3

In [5]:
rejections['Rejection_rate'] = (rejections['sample_case_rejections1'] + rejections['sample_case_rejections2'] + rejections ['sample_case_rejections3']) / (rejections['sample_case_count1'] + rejections['sample_case_count2'] + rejections['sample_case_count3'])

In [6]:
rejections

,date_received,ingredient_name,supplier,number_of_cases,units_per_case,sample_case_count1,sample_case_count2,sample_case_count3,sample_case_rejections1,sample_case_rejections2,sample_case_rejections3,Rejection_rate
0,10-Jun-21,tomato_cherry,ABC Vegetables,10,100,95,100,110,5,3,5,0.042623
1,10-Jun-21,tomato_cherry,Tomato Land,20,500,440,480,500,10,0,25,0.024648
2,10-Jun-21,tomato_vine,Tomato Land,25,100,100,100,100,0,0,0,0.000000
3,10-Jun-21,tomato_vine,ABC Vegetables,10,100,100,98,101,0,0,0,0.000000
4,10-Jun-21,cucumber_english,ABC Vegetables,14,50,51,50,51,10,0,0,0.065789
5,10-Jun-21,cucumber_pickle,Dill Farms,15,50,50,50,50,0,0,0,0.000000
6,11-Jun-21,bananas_organic,Banana Farms Inc,24,40,40,40,40,0,0,0,0.000000
7,11-Jun-21,bananas_organic,ABC Vegetables,26,30,30,28,29,0,3,0,0.034483
8,11-Jun-21,bananas_organic,Banana Farms Inc,20,30,30,30,30,0,0,0,0.000000
9,11-Jun-21,apples_gala,Orchard Inc,20,90,90,94,90,1,4,5,0.036496
10,11-Jun-21,apples_gala,Orchard Inc,5,90,90,90,90,0,0,3,0.011111
11,11-Jun-21,apples_gs,Orchard Inc,1,80,80,82,80,2,0,5,0.028926
12,13-Jun-21,apples_gala,Apple Farm,20,90,90,90,90,0,0,0,0.000000
13,13-Jun-21,oranges_california,Cali Fruits,20,90,90,90,90,4,0,0,0.014815
14,13-Jun-21,oranges_california,ABC Vegetables,40,100,100,102,101,0,0,3,0.009901
15,13-Jun-21,grapes_red,Cali Fruits,20,35,30,35,30,4,0,0,0.042105
16,13-Jun-21,grapes_green,Cali Fruits,10,35,35,35,30,5,5,3,0.130000

In [18]:
def threshold(x,y,z):
    if x >= 0:
        return f'Hi {z}, you have {x*100}% rejected of {y} products'

In [19]:
rejections['Notifications'] = rejections.apply(lambda x: threshold(x['Rejection_rate'], x['ingredient_name'], x['supplier']), axis=1)

In [20]:
rejections

,date_received,ingredient_name,supplier,number_of_cases,units_per_case,sample_case_count1,sample_case_count2,sample_case_count3,sample_case_rejections1,sample_case_rejections2,sample_case_rejections3,Rejection_rate,Notifications
0,10-Jun-21,tomato_cherry,ABC Vegetables,10,100,95,100,110,5,3,5,0.042623,"Hi ABC Vegetables, you have 4.2622950819672125..."
1,10-Jun-21,tomato_cherry,Tomato Land,20,500,440,480,500,10,0,25,0.024648,"Hi Tomato Land, you have 2.464788732394366% re..."
2,10-Jun-21,tomato_vine,Tomato Land,25,100,100,100,100,0,0,0,0.000000,"Hi Tomato Land, you have 0.0% rejected of toma..."
3,10-Jun-21,tomato_vine,ABC Vegetables,10,100,100,98,101,0,0,0,0.000000,"Hi ABC Vegetables, you have 0.0% rejected of t..."
4,10-Jun-21,cucumber_english,ABC Vegetables,14,50,51,50,51,10,0,0,0.065789,"Hi ABC Vegetables, you have 6.578947368421052%..."
5,10-Jun-21,cucumber_pickle,Dill Farms,15,50,50,50,50,0,0,0,0.000000,"Hi Dill Farms, you have 0.0% rejected of cucum..."
6,11-Jun-21,bananas_organic,Banana Farms Inc,24,40,40,40,40,0,0,0,0.000000,"Hi Banana Farms Inc, you have 0.0% rejected of..."
7,11-Jun-21,bananas_organic,ABC Vegetables,26,30,30,28,29,0,3,0,0.034483,"Hi ABC Vegetables, you have 3.4482758620689653..."
8,11-Jun-21,bananas_organic,Banana Farms Inc,20,30,30,30,30,0,0,0,0.000000,"Hi Banana Farms Inc, you have 0.0% rejected of..."
9,11-Jun-21,apples_gala,Orchard Inc,20,90,90,94,90,1,4,5,0.036496,"Hi Orchard Inc, you have 3.64963503649635% rej..."
10,11-Jun-21,apples_gala,Orchard Inc,5,90,90,90,90,0,0,3,0.011111,"Hi Orchard Inc, you have 1.1111111111111112% r..."
11,11-Jun-21,apples_gs,Orchard Inc,1,80,80,82,80,2,0,5,0.028926,"Hi Orchard Inc, you have 2.8925619834710745% r..."
12,13-Jun-21,apples_gala,Apple Farm,20,90,90,90,90,0,0,0,0.000000,"Hi Apple Farm, you have 0.0% rejected of apple..."
13,13-Jun-21,oranges_california,Cali Fruits,20,90,90,90,90,4,0,0,0.014815,"Hi Cali Fruits, you have 1.4814814814814816% r..."
14,13-Jun-21,oranges_california,ABC Vegetables,40,100,100,102,101,0,0,3,0.009901,"Hi ABC Vegetables, you have 0.9900990099009901..."
15,13-Jun-21,grapes_red,Cali Fruits,20,35,30,35,30,4,0,0,0.042105,"Hi Cali Fruits, you have 4.2105263157894735% r..."
16,13-Jun-21,grapes_green,Cali Fruits,10,35,35,35,30,5,5,3,0.130000,"Hi Cali Fruits, you have 13.0% rejected of gra..."

In [22]:
list_1 = []
for i in rejections['supplier']:
    list_1.append(i)

In [23]:
list_1

['ABC Vegetables',
 'Tomato Land',
 'Tomato Land',
 'ABC Vegetables',
 'ABC Vegetables',
 'Dill Farms',
 'Banana Farms Inc',
 'ABC Vegetables',
 'Banana Farms Inc',
 'Orchard Inc',
 'Orchard Inc',
 'Orchard Inc',
 'Apple Farm',
 'Cali Fruits',
 'ABC Vegetables',
 'Cali Fruits',
 'Cali Fruits']

In [24]:
set1 = set(list_1)

In [25]:
set1

{'ABC Vegetables',
 'Apple Farm',
 'Banana Farms Inc',
 'Cali Fruits',
 'Dill Farms',
 'Orchard Inc',
 'Tomato Land'}

In [27]:
rejections.set_index('supplier', inplace=True)

In [32]:
for i in set1:
   rejections.loc[i].to_csv(f'forgroup\{i}.csv')